### ISSUE TITLE
Error event from socket

### ISSUE THREAD

**Issue by jodibb** [codetheweb/tuyapi#158]
Hey guys,
After update to 4.0.3 version, I'm randomly facing exceptions.

js script:
````
const TuyAPI = require('tuyapi');

const device = new TuyAPI({
  id: 'xxxx',
  key: 'xxxx',
  ip: '10.1.0.10'});

(async () => {

var argv = require('minimist')(process.argv.slice(2));
	var settings = {};
	if (argv['sound'] == 'true'){
		settings['132'] = true;
	} else if (argv['sound'] == 'false'){
		settings['132'] = false;
	}
	if (argv['start'] == 'true'){
		settings['127'] = true;
	} else if (argv['start'] == 'false'){
		settings['127'] = false;
	}
	if (argv['mist'] == '1'){
		settings['123'] = '1';
	} else if (argv['mist'] == '2'){
		settings['123'] = '2';
	}
	if (argv['light'] == 'true'){
		settings['133'] = '00f6fc00b56464';
		settings['131'] = 3456;
		settings['125'] = true;
	} else if (argv['light'] == 'false'){
		settings['125'] = false;
	}
	if (argv['warning'] == 'true'){
		settings['133'] = 'fc0c0000036464';
		settings['125'] = true;
	}

	await device.find();

	await device.connect();
	if (argv['check'] == 'true') {
		status = await device.get({dps: 127});
		console.log('Current status:', status);
	} else if (argv['status'] == 'true') {
		let data = await device.get({schema: true});
		console.log('Data from device:', data);
	} else {
		await device.set({
			  multiple: true,
			  data: settings});
		console.log('device was changed');
		console.dir(settings);
	};
	device.disconnect();
})();
````

Exception:
````
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Error from socket
    at Socket.client.on.err (/home/openhabian/node_modules/tuyapi/index.js:391:30)
    at Socket.emit (events.js:189:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:607:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:784:10)
Emitted 'error' event at:
    at Socket.client.on.err (/home/openhabian/node_modules/tuyapi/index.js:391:16)
    at Socket.emit (events.js:189:13)
    [... lines matching original stack trace ...]
    at WriteWrap.afterWrite [as oncomplete] (net.js:784:10)

````
Debug Output:
```
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 10.1.0.10... +7ms
  TuyAPI Socket connected. +14ms
  TuyAPI GET Payload: +2ms
  TuyAPI { gwId: 'XXX', devId: 'XXX' } +1ms
  TuyAPI Error event from socket. 10.1.0.10 { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:782:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +24ms
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Error from socket
    at Socket.client.on.err (/home/openhabian/node_modules/tuyapi/index.js:391:30)
    at Socket.emit (events.js:189:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:607:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:784:10)
Emitted 'error' event at:
    at Socket.client.on.err (/home/openhabian/node_modules/tuyapi/index.js:391:16)
    at Socket.emit (events.js:189:13)
    [... lines matching original stack trace ...]
    at WriteWrap.afterWrite [as oncomplete] (net.js:784:10)

```
**Desktop:**
 - raspberian
 - Node 10.15.1 

Any idea what's wrong there? For me, repro is random. I didn't find proper repro steps. I'm starting same script with exact same parameters and in most cases it works, but sometimes it throw this exception.
Thanks

**Comment by ramon18** [comment]
I’ve a theory. It’s related with the initial “get” that is called automatically after a connection is estabilidade (after we call “connect”).
In my opinion it shouldn’t call “get” automatically as it may introduce protocol sequence errors in the poor devices.

A possible workaround is to bind on(“data”,...) and wait for the result of the automatic “get” result, then you can do any further processing.

**Comment by jodibb** [comment]
Ok, I'll try to switch it to asynchronous and will see. Thanks

**Comment by codetheweb** [comment]
@ramon18 may be right, in my (limited) testing it appears the `.get()` in `.connect()` may be the root cause of errors like this one.  I'll do further testing, but I may end up removing the initial get.

**Comment by jodibb** [comment]
OK, Still some random issues: :/
`sudo DEBUG=* node /home/openhabian/scripts/oilDiffuser.js --start=false --light=false --mist=1
start:false
mist:1
light:false
sound:undefined
warning:undefined
check:undefined
status:undefined
  TuyAPI Finding missing IP undefined or ID 07200205b4e62d21b99d +0ms
  TuyAPI Received UDP message. +3s
  TuyAPI UDP data: +3ms
  TuyAPI { ip: '10.1.0.10',
  TuyAPI   gwId: 'XXX',
  TuyAPI   active: 2,
  TuyAPI   ability: 0,
  TuyAPI   mode: 0,
  TuyAPI   encrypt: true,
  TuyAPI   productKey: 'XXX',
  TuyAPI   version: '3.1' } +1ms
  TuyAPI Connecting to 10.1.0.10... +12ms
  TuyAPI Socket connected. +15ms
Connected to device!
  TuyAPI GET Payload: +2ms
  TuyAPI { gwId: 'XXX', devId: 'XXX' } +0ms
  TuyAPI Error event from socket. 10.1.0.10 { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:782:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +10ms
Error! Error: Error from socket
    at Socket.client.on.err (/home/openhabian/node_modules/tuyapi/index.js:391:30)
    at Socket.emit (events.js:189:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:607:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:784:10)
  TuyAPI Socket closed: 10.1.0.10 +4ms
Disconnected from device.
  TuyAPI Disconnect +2s
`

**Comment by codetheweb** [comment]
Hey @jodibb and @ramon18, I just published v5.0.1 and I think it should fix these issues.

Let me know if it works.

**Comment by jodibb** [comment]
Hey @codetheweb 
Thanks for update,
Sorry for late answer but I was about to try it if it works. And still have some issues.
I'm not sure if is same issue as before but I got this one now:

```
/home/openhabian/node_modules/tuyapi/index.js:415
      this._setResolver(packet.payload);
           ^

TypeError: this._setResolver is not a function
    at TuyaDevice._packetHandler (/home/openhabian/node_modules/tuyapi/index.js:415:12)
    at packets.forEach.packet (/home/openhabian/node_modules/tuyapi/index.js:315:43)
    at Array.forEach (<anonymous>)
    at Socket.client.on.data (/home/openhabian/node_modules/tuyapi/index.js:311:19)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```

It's from latest 5.0.1 version. It's "random", so I'll try to reproduce it also in debug mode.

**Comment by codetheweb** [comment]
Hmm...

The first one is potentially an easy fix, I can just add a check to ensure `this._setResolver()` is defined.

The second is a bit trickier.  It looks like your device is unexpectedly breaking off connections.  I'm not sure if there's much I can do about that.

**Comment by codetheweb** [comment]
I just published v5.0.2 that may fix the first issue.

**Comment by ls819011** [comment]
I'm also getting socket error randomly using v.5.1.1. 
Running script 4 times in row I got socket error twice.
Attached are test script I run and output I got - [test+log.zip](https://github.com/codetheweb/tuyapi/files/3455377/test%2Blog.zip)
I guess running `.get()` in `.connect()` can cause an issue.
Also, I guess emitting of 'connect' event should be done right before exiting `.connect()`.

**Comment by codetheweb** [comment]
@ls819011 have you tried with v5.1.2?  It contains some bug fixes that may resolve the issues you're seeing.

**Comment by jodibb** [comment]
Will try, thanks for info.

**Comment by ls819011** [comment]
@codetheweb with v5.1.2 errors still occur randomly. See [20190816-debug.log](https://github.com/codetheweb/tuyapi/files/3508413/20190816-debug.log). I used the same code for test.

**Comment by ls819011** [comment]
@codetheweb Errors with v5.1.2 still occur. Much more seldom but still occur. Here is an output:
```
sergey@orangepiplus:~$ DEBUG=* node scripts/test.js
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.0.71... +24ms
  TuyAPI Socket connected. +21ms
Connected to device!
  TuyAPI GET Payload: +8ms
  TuyAPI { gwId: '850605253c71bf3e2092', devId: '850605253c71bf3e2092' } +0ms
Command sent...
  TuyAPI GET Payload: +38ms
  TuyAPI { gwId: '850605253c71bf3e2092', devId: '850605253c71bf3e2092' } +1ms
  TuyAPI Error event from socket. 192.168.0.71 { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +10ms
Error! Error: Error from socket
    at Socket.client.on.err (/home/sergey/node_modules/tuyapi/index.js:323:30)
    at Socket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:613:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)
  TuyAPI Socket closed: 192.168.0.71 +6ms
Disconnected from device.
  TuyAPI Disconnect +10s
sergey@orangepiplus:~$
```
I used the same code for testing but I removed all delays which previously exist.
Also, could you please explain why after setting `dps: { '1': false }` I receive data from device `dps: { '1': true, '101': '2', '102': 0 }`?

```
sergey@orangepiplus:~$ DEBUG=* node scripts/test.js
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.0.71... +24ms
  TuyAPI Socket connected. +217ms
Connected to device!
  TuyAPI GET Payload: +7ms
  TuyAPI { gwId: '850605253c71bf3e2092', devId: '850605253c71bf3e2092' } +1ms
Command sent...
  TuyAPI GET Payload: +39ms
  TuyAPI { gwId: '850605253c71bf3e2092', devId: '850605253c71bf3e2092' } +0ms
  TuyAPI Received data: 000055aa000000010000000a0000005c00000000a927d7778651058d77f8274099eca3cddae2e35c223b31636a5a50592a2ba4744381d5f7577a11d7aa59c0b061a0515dfe5789bff515a8167e7c505c7d28f49b317e810469a87a5a9c949555865d73b7f9b92f130000aa55 +22ms
  TuyAPI Parsed: +7ms
  TuyAPI { payload:
  TuyAPI    { devId: '850605253c71bf3e2092',
  TuyAPI      dps: { '1': true, '101': '2', '102': 0 } },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1 } +1ms
Data from device: { devId: '850605253c71bf3e2092',
  dps: { '1': true, '101': '2', '102': 0 } }
Boolean status of default property: true.
  TuyAPI SET Payload: +7ms
  TuyAPI { devId: '850605253c71bf3e2092',
  TuyAPI   gwId: '850605253c71bf3e2092',
  TuyAPI   uid: '',
  TuyAPI   t: 1565948142,
  TuyAPI   dps: { '1': false } } +0ms
  TuyAPI Received data: 000055aa000000020000000a0000005c00000000a927d7778651058d77f8274099eca3cddae2e35c223b31636a5a50592a2ba4744381d5f7577a11d7aa59c0b061a0515dfe5789bff515a8167e7c505c7d28f49b317e810469a87a5a9c949555865d73b70beb01380000aa55 +6ms
  TuyAPI Parsed: +2ms
  TuyAPI { payload:
  TuyAPI    { devId: '850605253c71bf3e2092',
  TuyAPI      dps: { '1': true, '101': '2', '102': 0 } },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 2 } +0ms
Data from device: { devId: '850605253c71bf3e2092',
  dps: { '1': true, '101': '2', '102': 0 } }
Boolean status of default property: true.
  TuyAPI Disconnect +4ms
Disconnecting...
  TuyAPI Socket closed: 192.168.0.71 +5ms
Disconnected from device.
sergey@orangepiplus:~$

```
Thank you.

**Comment by codetheweb** [comment]
@ls819011 nothing looks wrong in the debug output, which makes me think it's probably an issue with your device or network.  Do you have anything else attempting to connect to the device?  The app could be affecting it even if it's in the background.

The device sends its updated state after a request to set state, resulting in the data you see.

I'm closing this issue for now as v5.0.0 and above should have fixed these types of problems, please create a new GitHub issue if you're able to demonstrate that TuyAPI is at fault.
