### ISSUE TITLE
Error from socket 

### ISSUE THREAD

**Issue by masipulami** [codetheweb/tuyapi#226]
Running the following command produces an error:

```
pi@raspberrypi:~ $ DEBUG=* tuya-cli get --ip 192.168.178.42 --id 38272685dc4f22e92563 --key 68379fd576eb1963 -a
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.178.42... +28ms
  TuyAPI Socket connected. +22ms
  TuyAPI GET Payload: +8ms
  TuyAPI { gwId: '38272685dc4f22e92563', devId: '38272685dc4f22e92563' } +1ms
  TuyAPI Error event from socket. 192.168.178.42 { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +36ms
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error from socket
    at Socket.client.on.err (/usr/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:365:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at onwriteError (_stream_writable.js:417:12)
    at onwrite (_stream_writable.js:439:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at Socket._destroy (net.js:568:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:870:10)
```

The IP is "pingable" and for sure correct. ID and key have been extracted using Charles.

My installation should be ok. No updates in the pipe.

```
sudo apt-get update
sudo apt-get upgrade
```

were run.

Any idea?

**Comment by Apollon77** [comment]
EPIPE normally happens when someone tries to write into a closed network socket

**Comment by masipulami** [comment]
So it‘s a bug or rather a device related issue?

Is there a way out of this?

**Comment by kueblc** [comment]
Did you try without `--ip`?

**Comment by kueblc** [comment]
Another thought - is your device running the new TLS firmware?

You can try running `nc -ulkp 6666` and `nc -ulkp 6667`. If you see plaintext out of 6666, you're running the old firmware (good). If you see garbage out of 6667, you're running the new firmware, which `tuya-cli` hasn't been updated to use.

**Comment by masipulami** [comment]
Ok. Thanks. I will try tomorrow morning.

What are the exact commands I have to run with regards to your second comment.

I will also try to run without -ip.

**Comment by kueblc** [comment]
The exact commands are just as I said, `nc -ulkp 6666` and `nc -ulkp 6667`. This assumes you have `nc` installed, which depends on your platform.

**Comment by masipulami** [comment]
OK, this is what I get with:

`nc -ulkp 6666`

`pi@raspberrypi:~ $ nc -ulkp 6666
U▒▒{"ip":"192.168.178.22","gwId":"02068131807d3a4f5ea2","active":2,"ability":0,"mode":0,"encrypt":true,"productKey":"qxJSyTLEtX5WrzA9","version":"3.1"}k▒▒UU▒▒{"ip":"192.168.178.22","gwId":"02068131807d3a4f5ea2","active":2,"ability":0,"mode":0,"encrypt":true,"productKey":"qxJSyTLEtX5WrzA9","version":"3.1"}k▒▒UU▒▒{"ip":"192.168.178.22","gwId":"02068131807d3a4f5ea2","active":2,"ability":0,"mode":0,"encrypt":true,"productKey":"qxJSyTLEtX5WrzA9","version":"3.1"}k▒▒UU▒▒{"ip":"192.168.178.22","gwId":"02068131807d3a4f5ea2","active":2,"ability":0,"mode":
...
...`


and this is what I get with `nc -ulkp 6667`:

`pi@raspberrypi:~ $ nc -ulkp 6667
U▒▒Зfgo3i▒▒▒▒2▒*u▒▒KM▒͠
ގ▒0▒#▒뉂AxV▒٬▒▒nz,▒▒    ▒▒6▒▒▒UW▒\▒ue▒#▒F▒▒x▒/ں▒▒▒▒▒▒JGEa6w7▒}h▒$V&▒F8▒*▒N▒d▒▒Ī
▒b▒▒j▒▒!{▒▒{"▒▒▒▒
                 8Cc▒▒▒pZ▒▒ŕ▒▒%eH▒UU▒▒Зfgo3i▒▒▒▒2▒*u▒▒KM▒͠
ގ▒0▒#▒뉂AxV▒٬▒▒nz,▒▒    ▒▒6▒▒▒UW▒\▒ue▒#▒F▒▒x▒/ں▒▒▒▒▒▒JGEa6w7▒}h▒$V&▒F8▒*▒N▒d▒▒Ī
▒b▒▒j▒▒!{▒▒{"▒▒▒▒
...`

Does not look promising I guess.

Is an update for the new firmware planned?

**Comment by kueblc** [comment]
Yes it does look like you are running the new firmware. `tuyapi` has already been updated for this firmware, it shouldn't take long to update `tuya-cli`. You can try using `tuyapi` directly for now.

**Comment by masipulami** [comment]
Ok. So I will wait.

I also have an issue connecting to the device via the NodeRed tuya node.

Probably due to the same reason.

Is there also an update planned?

**Comment by kueblc** [comment]
I don't have any relation to the NodeRED plugin, so I couldn't say. You might try making the adjustment yourself, it could be as simple as updating the version of `tuyapi` used.

**Comment by codetheweb** [comment]
@masipulami I just merged in a PR on the CLI repo that adds support for v3.3 firmware, published in v1.7.0 of `@tuaypi/cli`.  Please update the package and try it out.

**Comment by masipulami** [comment]
Thanks. It worked. 👍

**Comment by andy0172** [comment]
Hi and thanks for all this work. It was all fine until I clicked on update firmware for my tuya sockets :-(

Now I have updated to the latest version, but still get the same error like in the initial post:
TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.178.74... +16ms
  TuyAPI Socket connected. +27ms
  TuyAPI GET Payload: +5ms
  TuyAPI { gwId: '18122702600194bff1eb', devId: '18122702600194bff1eb' } +1ms
  TuyAPI Error event from socket. 192.168.178.74 { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +22ms
events.js:183                                                                                                                                                                                                 
      throw er; // Unhandled 'error' event                                                                                                                                                                    
      ^                                                                                                                                                                                                       
                                                                                                                                                                                                              
Error: Error from socket                                                                                                                                                                                      
    at Socket.client.on.err (/usr/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:323:30)                                                                                                           
    at emitOne (events.js:116:13)                                                                                                                                                                             
    at Socket.emit (events.js:211:7)                                                                                                                                                                          
    at onwriteError (_stream_writable.js:417:12)                                                                                                                                                              
    at onwrite (_stream_writable.js:439:5)                                                                                                                                                                    
    at _destroy (internal/streams/destroy.js:39:7)                                                                                                                                                            
    at Socket._destroy (net.js:568:3)                                                                                                                                                                         
    at Socket.destroy (internal/streams/destroy.js:32:8)                                                                                                                                                      
    at WriteWrap.afterWrite [as oncomplete] (net.js:870:10)   

Details of tuya socket:
MCU Modul 1.0.7
Wi-Fi Modul 1.0.7

Strange behavior, with the same installation I can turn on and off a tuya light with this details:
MCU Modul 1.1.1
Wi-Fi Modul 1.1.1
